server:
  port: 8888
spring:
  application:
    name: gatewayserver
  cloud:
    config:
      enabled: false
    discovery:
      enabled: true
    gateway:
#      routes:
#        - id : r1
#          uri : lb://MARQUE
#          predicates:
#            - Path=/api/marques/**
#        - id: r2
#          uri: lb://VOITURE
#          predicates:
#            - Path=/api/voitures/**
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:8090/realms/master/protocol/openid-connect/certs"
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    gateway:
      access: unrestricted
eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}
      instance:
        prefer-ip-address: true
resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000