server:
  port: 8888
spring:
  application:
    name: gatewayserver
  cloud:
    config:
      enabled: false
    discovery:
      enabled: true
    gateway:
      routes:
        - id : r1
          uri : lb://MARQUE
          predicates:
            - Path=/api/marques/**
        - id: r2
          uri: lb://VOITURE
          predicates:
            - Path=/api/voitures/**
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
  eureka:
    client:
      service-url:
        defaultZone: 'http://localhost:8761/eureka/'
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    gateway:
      access: unrestricted
eureka:
  instance:
    prefer-ip-address: true