spring:
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
  application:
    name: "configserver"
  profiles:
    active: git
      #native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zinadarras/config-repo.git
          default-label: main
          clone-on-start: true
        #native:
          #search-locations: file:///C:/Users/zinad/IdeaProjects/zaina-spring-cloud/config-repo
          #search-locations: "classpath:/config"

server:
  port: 9999
management:
  endpoints:
    web:
      exposure:
        include: '*'