spring:
#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"
  profiles:
    active: "default"
  config:
    import: optional:configserver:${CONFIG_SERVICE_URL:http://localhost:9999}


  application:
    name: marque
  datasource:
#    url : jdbc:mysql://mysqldb:3306/test?useSSL=false&serverTimezone=UTC
#    username: root
#    password: root
    url: 'jdbc:h2:mem:marquedb'
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  cloud:
    config:
      enabled: true
    discovery:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
    hostname: localhost
build:
  version : "1.0"
author:
  name: "Zaina AL DARRAS"
  email: "zinadarras41@gmail.com"