spring:
  profiles:
    active: "prod"
  config:
    import: "optional:configserver:http://localhost:9999/"

  application:
    name: marque
  datasource:
    url: 'jdbc:h2:mem:marquedb'
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  cloud:
    config:
      enabled: true
    discovery:
      enabled: true
  eureka:
    client:
      service-url:
        defaultZone: 'http://localhost:8761/eureka/'
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  instance:
    prefer-ip-address: true
